version: "2.2"

services:
  mongo:
    image: mongo:5.0.4
    container_name: food_store_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db:rw
      - ./init:/docker-entrypoint-initdb.d

  auth:
    image: wi4er/doppelganger:0.5.1
    container_name: food_store_auth
    environment:
      DB_HOST: mongo
      DB_USER: auth
      DB_PASSWORD: example
      CACHE_HOST: cache
    links:
      - mongo
      - cache
    ports:
      - "8081:8080"

#  admin:
#    image: wi4er/admin:0.0.3
#    container_name: cerberus_admin
#    ports:
#      - "8082:8080"
#    volumes:
#      - ./settings/auth.json:/app/build/auth.json
#      - ./settings/services.json:/app/build/services.json

  cache:
    image: redis:alpine
    container_name: cerberus_cache
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/
